### ISSUE TITLE
Bug - On BSC subgraph ethPriceUSD is returning the price of BNB and not ETH

### ISSUE THREAD

**Issue by kazazor** [Uniswap/v3-subgraph#163]
This is a bug when [running the query](https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-bsc/graphql?query=%7B%0A++++ethPriceUSD%3A+bundles%28first%3A+1%29+%7B%0A++++++ethPriceUSD%0A++++%7D%0A++%7D):
```
{
    ethPriceUSD: bundles(first: 1) {
      ethPriceUSD
    }
  }
```

You get the result:
```
{
  "data": {
    "ethPriceUSD": [
      {
        "ethPriceUSD": "318.8462933395146456248972108231449"
      }
    ]
  }
}
```

Which is the current price of BNB and not ETH:
![Screenshot 2023-04-12 at 15 33 38](https://user-images.githubusercontent.com/1577655/231458467-5efaba2e-6c96-47ab-8614-8826e5e5865d.png)

At first I thought maybe it was supposed to be `nativeTokenPriceUSD` and not `eth`, but on Polygon it does return eth parice and not matic's. So it's a bug on BSC.

**Comment by burgossrodrigo** [comment]
Yeah but by ETH they mean the currency of the chain, so it should be be BNB.
