### ISSUE TITLE
how can I get the tick's volume locked in a pool?

### ISSUE THREAD

**Issue by huyutao3550346** [Uniswap/v3-subgraph#19]
hello I want get each tick's volume locked in pool. such as USDC/ETH. 
![image](https://user-images.githubusercontent.com/29395068/121803442-2a20d700-cc74-11eb-8561-e0923dd47370.png)
I have try to this:
```javascprit
fragment PoolFields on Pool {
    id
    txCount
  	sqrtPrice
		token0
  {
    decimals
  }
  token1
  {
    decimals
  }
    ticks(first:5,where:{
      pool:"0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
    },orderBy:liquidityGross,orderDirection:desc){
    	tickIdx
    	liquidityGross
    	liquidityNet
    	price0
    	price1
    }
    token0Price
  	token1Price
   liquidityProviderCount
  } query {
    pools(first: 1, orderBy: totalValueLockedUSD, orderDirection: desc, where: { volumeUSD_gt:0 }) {
      ...PoolFields
    }
  }
```
and the result is 
![image](https://user-images.githubusercontent.com/29395068/121803739-80424a00-cc75-11eb-87c1-c0b7ac151763.png)

but the result haven't info .what API should I invoke? or convert liquidityGross liquidityNet?

**Comment by ticruz38** [comment]
you can query volumeUSD under the ticks field

**Comment by huyutao3550346** [comment]
Thank you for answering my questions.
I have tried but the volumeUSD under the ticks fiels also get 0...
I query in this url:https://thegraph.com/explorer/subgraph/ianlapham/uniswap-v3-prod
here is my sql:
fragment ticksfield on Tick {
    id
    volumeUSD
  	
  } query {
    ticks(first: 10, orderBy: volumeUSD, orderDirection: desc) {
      ...ticksfield
    }
  }

and result is:
![image](https://user-images.githubusercontent.com/29395068/124573351-0c621e80-de7c-11eb-9cfe-c7dbf17a0db0.png)

I noticed that the volumeUSD of tick is always set to ZERO_BD in https://github.com/Uniswap/uniswap-v3-subgraph/blob/main/src/utils/tick.ts
![image](https://user-images.githubusercontent.com/29395068/124573307-ffddc600-de7b-11eb-94de-7ee314ae5006.png)

**Comment by ticruz38** [comment]
indeed, I do have 0 for each tick as well

**Comment by TonyZhangkz** [comment]
same issue here - I don't seem to be able to find any data regarding ticks

**Comment by jarry-xiao** [comment]
Bumping this issue. This is basically the whole point of having UniV3, so accessing this volumeUSD field is pretty important

**Comment by scvsh** [comment]
Is there any other method of getting the pool liquidity distribution, since we can't query thegraph for this?

**Comment by sydneyhenrard** [comment]
I think it's not yet implemented see https://github.com/Uniswap/uniswap-v3-subgraph/blob/main/src/mappings/core.ts#L145

**Comment by huyutao3550346** [comment]
also see dune.
https://dune.xyz/yulesa/Liquidity-Distribution
