### ISSUE TITLE
indexing error on mainnet (Last Synced Block 19473885) 

### ISSUE THREAD

**Issue by Bitwise0x** [Uniswap/v3-subgraph#205]
**Input:**
{
  factories(first: 5) {
    id
    poolCount
    txCount
    totalVolumeUSD
  }
  bundles(first: 5) {
    id
    ethPriceUSD
  }
}

**output:** 
{
  "errors": [
    {
      "message": "indexing_error"
    }
  ]
}

**Comment by k1tzu** [comment]
I don't understand this either. Graph explorer shows the error and how everyone else are working with Uniswap API? https://thegraph.com/hosted-service/subgraph/uniswap/uniswap-v3

**Comment by Alex-ASF** [comment]
Confirmed. And I think that due to this the liquidity diagram does not appear when adding liquidity.
![addl_no_d_1_2](https://github.com/Uniswap/v3-subgraph/assets/36363017/45aad125-fc22-4929-8839-65481c03ab67)

**Comment by Alex-ASF** [comment]
Looks like they fixed it.

**Comment by Bitwise0x** [comment]
Fixed
