### ISSUE TITLE
Found a tick's bug in subgraph

### ISSUE THREAD

**Issue by huyutao3550346** [Uniswap/v3-subgraph#44]
hello guys, in the v3 whitePaper we can see the tick's feeGrowthOutside{0,1}
![image](https://user-images.githubusercontent.com/29395068/129177754-487c28e8-7029-483c-8127-907c49f686cd.png)
that means when priceNow is bewteen tickLower and tickUpper. 
feeGrowthInside{0,1} = feeGrowthGlobal{0,1} - tickLower.feeGrowthOutside{0,1}  - tickUpper.feeGrowthOutside{0,1}. like 
![365d464e141ac8a64316aa91f582e71](https://user-images.githubusercontent.com/29395068/129188821-8e5ecbf8-d0ba-45b0-948c-279a580a2786.png)
but when I query the subgrah return wrong answer.

here is the query
--------------------------------------
{
  ticks(where:{
    pool_contains:"0x4e68ccd3e89f51c3074ca5072bbac773960dfa36"
    tickIdx_in:[
      -195660,
      -195900]
  }
  block:{number:13010089}
  )
  {
    tickIdx
    feeGrowthOutside0X128
    feeGrowthOutside1X128
    pool
    {
      tick
      feeGrowthGlobal0X128
      feeGrowthGlobal1X128
    }
  }
}

here is the result:
--------------------------------------
{
  "data": {
    "ticks": [
      {
        "feeGrowthOutside0X128": "335883582520604181952009590658028448194028",
        "feeGrowthOutside1X128": "854216468588660062387455627429334",
        "pool": {
          "feeGrowthGlobal0X128": "337450237140301366713991986895478281593300",
          "feeGrowthGlobal1X128": "858801197364324603853037591152213",
          "tick": "-195807"
        },
        "tickIdx": "-195660"
      },
      {
        "feeGrowthOutside0X128": "281801500759483248405854115923760248801301",
        "feeGrowthOutside1X128": "657493057862399273342033321023185",
        "pool": {
          "feeGrowthGlobal0X128": "337450237140301366713991986895478281593300",
          "feeGrowthGlobal1X128": "858801197364324603853037591152213",
          "tick": "-195807"
        },
        "tickIdx": "-195900"
      }
    ]
  }
}

as you see the current tick is -195807 and if I set the range in [-195900,-195660].
the feeInside0 = (feeGrowthGlobal0X128 - tickLower.feeGrowthOutside0X128 -  tickUpper.feeGrowthOutside0X128)/(2^128);
but get feeInside0 = -823.53619 Less than 0.
is that have question?

**Comment by mariorz** [comment]
Hi. I wrote a test to compare subgraph data with blockchain data at the specified block to confirm the issue you are seeing.  uploaded [here](https://gist.github.com/mariorz/bf005b6ec8c9838b805e1dba60a593aa). Use brownie to run it: `brownie run tickstest.py --network mainnet`. 

Results:
```
Testing contract calls vs the graph values for
pool:0x4e68ccd3e89f51c3074ca5072bbac773960dfa36
tick:-195660
block:13010089
feeGrowthOutside0X128 from the blockchain: 1067292557275396938893002967958758719094
feeGrowthOutside0X128 from the graph     : 335883582520604181952009590658028448194028
Mismatch ✘

```

There is a mismatch between blockchain data and subgraph data.

**Comment by huyutao3550346** [comment]
well mariorz I also found this problem, the subgraph data was wrong... so I monitor the uniswap's event to dump data in Ethereum Main Network and refer to the logic of this project. finaly I got the correct data.

**Comment by huyutao3550346** [comment]
> Hi. I wrote a test to compare subgraph data with blockchain data at the specified block to confirm the issue you are seeing. uploaded [here](https://gist.github.com/mariorz/bf005b6ec8c9838b805e1dba60a593aa). Use brownie to run it: `brownie run tickstest.py --network mainnet`.
> 
> Results:
> 
> ```
> Testing contract calls vs the graph values for
> pool:0x4e68ccd3e89f51c3074ca5072bbac773960dfa36
> tick:-195660
> block:13010089
> feeGrowthOutside0X128 from the blockchain: 1067292557275396938893002967958758719094
> feeGrowthOutside0X128 from the graph     : 335883582520604181952009590658028448194028
> Mismatch ✘
> ```
> 
> There is a mismatch between blockchain data and subgraph data.

well mariorz I also found this problem, the subgraph data was wrong... so I monitor the uniswap's event to dump data in Ethereum Main Network and refer to the logic of this project. finaly I got the correct data.

**Comment by ackvf** [comment]
@huyutao3550346 So you basically do your own indexing and calculate the required data yourself using the formulas from the whitepaper? While it proves that the formulas are correct, it still doesn't solve the issue and that is that the calculation implementation in this project is wrong. Might reconsider reopening this issue again.
