### ISSUE TITLE
Get liquidity positions for a particular pool

### ISSUE THREAD

**Issue by yogesh-bansal** [Uniswap/v3-subgraph#99]
UniswapV2 graph had the `liquidityPosition` entity under a pool entity, so I could filter based on pool address and then get the LPs.

But in UniswapV3 graph, The `Positions` Entity is on top level, So to get a particular pool's LPs I have to get all the LPs and then filter based on the pool address, It becomes computationally extensive as there are a large number of LPs and we can only get them in batches of 1000.

Is there a alternate route I am missing to get the LPs for a particular pool directly?

**Comment by npip99** [comment]
See the "where" clause in https://docs.uniswap.org/sdk/subgraph/subgraph-examples#historical-global-data

Then you can get batches of 1000, after having them already filtered by pool address.

**Comment by yogesh-bansal** [comment]
Can you help with an example, The issue I am facing is, The position entity is at top so I am unable to filter the position data based on a pool address.
<img width="177" alt="image" src="https://user-images.githubusercontent.com/8408205/167072456-9bf613be-5ca5-4412-a06d-b924b7c9aaca.png">

**Comment by npip99** [comment]
@yogesh-bansal 

```
{
   positions(                                                                                                                                                                                                
     block: {number: 13286545},   
     first: 1000,
     skip: 0,
     where: {
       pool: "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640",
       liquidity_gt: 0,
    }) {
         id,
         ...
}
```

An example of a where clause. "Skip" can be adjusted to iterate over the list.

**Comment by yogesh-bansal** [comment]
```
{
   positions(                                                                                                                                                                                                
     block: {number: 13286545},   
     first: 1000,
     skip: 0,
     where: {
       pool: "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640",
       liquidity_gt: 0,
     },
   ) {
         id
  }}
  ```
  Made Some minor Changes, Now it works thanks.
